modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/IoeCmcomc/command_extractor/issues"
license = "MIT License"

[[mods]]
modId = "command_extractor"
version = "${version}"
displayName = "Command extractor"
authors = "IoeCmcomc"
description = '''
A Minecraft mod to extract available server commands to a JSON file.
'''
logoFile = "command_extractor_icon.png"
displayURL = "https://github.com/IoeCmcomc/command_extractor"

[[dependencies.command_extractor]]
modId = "forge"
mandatory = true
versionRange = "[49,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.command_extractor]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.command_extractor]]
modId = "architectury"
mandatory = true
versionRange = "[11.1.17,)"
ordering = "AFTER"
side = "BOTH"

[modproperties.command_extractor]
   catalogueImageIcon="command_extractor_icon.png"