modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/IoeCmcomc/command_extractor/issues"
license = "MIT License"

[[mods]]
modId = "command_extractor"
version = "${version}"
displayName = "Command extractor"
authors = "IoeCmcomc"
description = '''
A Minecraft mod to extract available server commands to a JSON file.
'''
logoFile = "command_extractor_icon.png"
displayURL = "https://github.com/IoeCmcomc/command_extractor"

[[dependencies.command_extractor]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.command_extractor]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.command_extractor]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[modproperties.command_extractor]
   catalogueImageIcon="command_extractor_icon.png"

[[mixins]]
config = "command_extractor.mixins.json"